People counter app from Scrimba courses
mamatkulov95/people-counter-app pull request #1
Opened 2022-09-04 04:18 UTC by mamatkulov95

People counter app from Scrimba courses.
![image](https://user-images.githubusercontent.com/49342620/188297184-f62346a0-6153-41e9-950e-e82f93fb39e1.png)

2022-09-06 14:11 UTC, KetanKBaboo commented on script.js
> +event.preventDefault()
What is the purpose of this line? event.preventDefault( ) is used when an element triggers an action by any specified event like "click" and you want to stop that action from happening. Suppose. you wish to submit a form through submit button and you have used form element. So, the default action of form submission is to reload the page. Here, you can stop this page reload by the preventDefault method.

2022-09-07 00:40 UTC, abanseka requested changes
NOTE:

:heavy_check_mark:  You Did an awesome Job!
However when you write js within HTML you have very little control
especially when it comes to keeping your code optimized and modularized
essentially making it more maintainable.

🛑 - the event object you used mostly applies in things like form inputs
with a submit event. this is because by default, submitting a form will reload
the entire page and in scenarios where you don't want that, you can then use it.

TO-DO:

- start by selecting all elements that you'll interact with at the top level
- Extract your functionality with functions 😂 (it's in the name)
- when ever possible optimize your code ie
  - start by making it work 
  - Refactor aka rinse and repeat.

🛑 - Please use more of classes in HTML, this is because id's are mostly
used to uniquely identify particular items maybe for the purpose of
navigating a web page (jump to section) also it's advised to have at
most one id on for any element unlike classes where you can have multiple
elements

- Please remember to avoid applying styles directly to HTML elements CSS lines `7` and `41`

2022-09-12 15:07 UTC, mamatkulov95 commented on script.js
> +event.preventDefault()
Removed.

2022-09-26 08:57 UTC, abanseka approved these changes

2022-09-26 08:57 UTC, merged